<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="0" hostname="DIT004281" name="pytest" skipped="0" tests="8" time="0.136" timestamp="2024-06-27T05:15:19.318995"><testcase classname="core.tests.test_views" file="core/tests/test_views.py" line="34" name="test_x_forwarded_for_not_set[get_kwargs0]" time="0.038"><system-err>2024-06-27 05:15:19,404 INFO ProxyView created
2024-06-27 05:15:19,404 ERROR HTTP_X_FORWARDED_FOR was missing from the request &lt;WSGIRequest: GET &apos;/sso/accounts/login/&apos;&gt;. This is not expected: later IP whitelisting will fail.
2024-06-27 05:15:19,404 ERROR REMOTE_ADDR was missing from the request &lt;WSGIRequest: GET &apos;/sso/accounts/login/&apos;&gt;. This is not expected: later IP whitelisting will fail.
2024-06-27 05:15:19,405 INFO Normalizing response headers
2024-06-27 05:15:19,405 INFO Checking for invalid cookies
</system-err></testcase><testcase classname="core.tests.test_views" file="core/tests/test_views.py" line="34" name="test_x_forwarded_for_not_set[get_kwargs1]" time="0.002"><system-err>2024-06-27 05:15:19,408 INFO ProxyView created
2024-06-27 05:15:19,408 ERROR HTTP_X_FORWARDED_FOR was missing from the request &lt;WSGIRequest: GET &apos;/sso/accounts/login/&apos;&gt;. This is not expected: later IP whitelisting will fail.
2024-06-27 05:15:19,408 ERROR REMOTE_ADDR was missing from the request &lt;WSGIRequest: GET &apos;/sso/accounts/login/&apos;&gt;. This is not expected: later IP whitelisting will fail.
2024-06-27 05:15:19,408 INFO Normalizing response headers
2024-06-27 05:15:19,409 INFO Checking for invalid cookies
</system-err></testcase><testcase classname="core.tests.test_views" file="core/tests/test_views.py" line="34" name="test_x_forwarded_for_not_set[get_kwargs2]" time="0.002"><system-err>2024-06-27 05:15:19,411 INFO ProxyView created
2024-06-27 05:15:19,411 ERROR REMOTE_ADDR was missing from the request &lt;WSGIRequest: GET &apos;/sso/accounts/login/&apos;&gt;. This is not expected: later IP whitelisting will fail.
2024-06-27 05:15:19,411 INFO Normalizing response headers
2024-06-27 05:15:19,411 INFO Checking for invalid cookies
</system-err></testcase><testcase classname="core.tests.test_views" file="core/tests/test_views.py" line="58" name="test_if_x_forwarded_for_and_remote_addr_then_are_concat_with_comma" time="0.002"><system-err>2024-06-27 05:15:19,413 INFO ProxyView created
2024-06-27 05:15:19,414 INFO Normalizing response headers
2024-06-27 05:15:19,414 INFO Checking for invalid cookies
</system-err></testcase><testcase classname="core.tests.test_views" file="core/tests/test_views.py" line="71" name="test_get_upstream_response_http_error_logged_and_raised" time="0.003"><system-err>2024-06-27 05:15:19,416 INFO ProxyView created
2024-06-27 05:15:19,416 ERROR Fake problem
Traceback (most recent call last):
  File &quot;/Users/davidurquhart/great/directory-sso-proxy/core/views.py&quot;, line 160, in get_upstream_response
    upstream_response = self.http.urlopen(
  File &quot;/Users/davidurquhart/.pyenv/versions/3.9.13/lib/python3.9/unittest/mock.py&quot;, line 1092, in __call__
    return self._mock_call(*args, **kwargs)
  File &quot;/Users/davidurquhart/.pyenv/versions/3.9.13/lib/python3.9/unittest/mock.py&quot;, line 1096, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File &quot;/Users/davidurquhart/.pyenv/versions/3.9.13/lib/python3.9/unittest/mock.py&quot;, line 1151, in _execute_mock_call
    raise effect
urllib3.exceptions.HTTPError: Fake problem
</system-err></testcase><testcase classname="core.tests.test_views" file="core/tests/test_views.py" line="90" name="test_post_password_reset_with_token" time="0.002"><system-err>2024-06-27 05:15:19,419 INFO ProxyView created
</system-err></testcase><testcase classname="core.tests.test_views" file="core/tests/test_views.py" line="107" name="test_post_password_reset_with_token_and_csrfmiddleewaretoken" time="0.001"><system-err>2024-06-27 05:15:19,422 INFO ProxyView created
</system-err></testcase><testcase classname="healthcheck.tests.test_views" file="healthcheck/tests/test_views.py" line="3" name="test_pingdom_app_healthcheck_ok" time="0.001"></testcase></testsuite></testsuites>